#!/usr/bin/env python3
"""
Integration test for Ewald sphere correction with s2 spatial frequency mode.

Ewald sphere correction is enabled via ``--ewald`` in ``relion_refine_mpi``.
The test verifies that the flag is accepted and that refinement completes
successfully with the s2 spatial-frequency mode.

Uses purely synthetic Gaussian-blob particles and a RELION5-format STAR file
generated by fixtures.py.  No tutorial data is required.
"""

from pathlib import Path

import pytest


_COMMON_ARGS = [
    "--ini_high", "40",
    "--ctf",
    "--tau2_fudge", "4",
    "--particle_diameter", "25",
    "--flatten_solvent",
    "--zero_mask",
    "--oversampling", "1",
    "--healpix_order", "1",
    "--offset_range", "5",
    "--offset_step", "2",
    "--sym", "c1",
    "--norm",
    "--scale",
    "--j", "2",
    "--spatial_frequency_mode", "s",
]


@pytest.mark.integration
class TestEwald:
    """Test suite for Ewald sphere correction with s2 mode."""

    def test_ewald_s2_mode(self, test_data_dir, relion_bin, fixtures_module, relion_runner):
        """Test 3D classification with Ewald sphere correction and s2 mode."""
        paths = fixtures_module["generate_test_dataset"](
            str(test_data_dir), relion_bin, relion_runner,
            num_particles=12,
            size=32,
            angpix=1.0,
        )

        assert Path(paths["particles_mrc"]).exists()
        assert Path(paths["star_file"]).exists()

        output_dir = test_data_dir / "ewald"
        output_dir.mkdir(parents=True, exist_ok=True)

        cmd = [
            "mpirun", "-n", "2",
            str(relion_bin / "relion_refine_mpi"),
            "--i", str(test_data_dir / "particles.star"),
            "--o", str(output_dir / "run"),
            "--ref", str(test_data_dir / "initial_model.mrc"),
            "--K", "1",
            "--iter", "1",
            "--ewald",
        ] + _COMMON_ARGS

        result = relion_runner(cmd, timeout=600)
        assert result.returncode == 0, f"RELION Ewald test failed:\n{result.stderr}"

        assert (output_dir / "run_it001_model.star").exists(), "Model star file not found"

    def test_ewald_two_iterations(self, test_data_dir, relion_bin, fixtures_module, relion_runner):
        """Test Ewald sphere correction across 2 iterations with s2 mode."""
        fixtures_module["generate_test_dataset"](
            str(test_data_dir), relion_bin, relion_runner,
            num_particles=14,
            size=32,
            angpix=1.0,
        )

        output_dir = test_data_dir / "ewald_iter"
        output_dir.mkdir(parents=True, exist_ok=True)

        cmd = [
            "mpirun", "-n", "2",
            str(relion_bin / "relion_refine_mpi"),
            "--i", str(test_data_dir / "particles.star"),
            "--o", str(output_dir / "run"),
            "--ref", str(test_data_dir / "initial_model.mrc"),
            "--K", "1",
            "--iter", "2",
            "--ewald",
        ] + _COMMON_ARGS

        result = relion_runner(cmd, timeout=600)
        assert result.returncode == 0
        assert (output_dir / "run_it002_model.star").exists()
