#!/usr/bin/env python3
"""
Integration test for 3D reconstruction with s2 spatial frequency mode.

Uses purely synthetic Gaussian-blob particles and a RELION5-format STAR file
generated by fixtures.py.  No tutorial data is required.
"""

from pathlib import Path

import pytest

from fixtures import reconstruct_and_check_fsc


@pytest.mark.integration
class TestReconstruction:
    """Test suite for 3D reconstruction with s2 mode."""

    def test_reconstruction_s2_mode(self, test_data_dir, relion_bin, fixtures_module, relion_runner):
        """Test basic 3D reconstruction with s2 spatial frequency mode."""
        paths = fixtures_module["generate_test_dataset"](
            str(test_data_dir), relion_bin, relion_runner,
            num_particles=64,
            size=32,
            angpix=1.0,
        )

        assert Path(paths["particles_mrc"]).exists()
        assert Path(paths["star_file"]).exists()

        output_dir = test_data_dir / "reconstruction"
        output_dir.mkdir(parents=True, exist_ok=True)

        cmd = [
            "mpirun", "-n", "2",
            str(relion_bin / "relion_reconstruct_mpi"),
            "--i", str(test_data_dir / "particles.star"),
            "--o", str(output_dir / "recon_"),
            "--spatial_frequency_mode", "s2",
            "--angpix", "1.0",
        ]

        result = relion_runner(cmd, timeout=300)
        assert result.returncode == 0, f"RELION reconstruction failed:\n{result.stderr}"

        # relion_reconstruct_mpi writes a Spider-format map with the given prefix
        output_map = output_dir / "recon_.spi"
        assert output_map.exists(), "Reconstruction output map not found"

        # FSC check: reconstruct from the input STAR (known orientations) and
        # compare against ground truth. Must exceed 0.5 at half Nyquist.
        reconstruct_and_check_fsc(
            Path(paths["star_file"]), Path(paths["initial_model"]),
            size=32, angpix=1.0,
            relion_bin=relion_bin, relion_runner=relion_runner,
            output_dir=output_dir,
        )

    def test_reconstruction_output_size(self, test_data_dir, relion_bin, fixtures_module, relion_runner):
        """Test that reconstruction output is non-trivial in size and meets FSC criterion."""
        paths = fixtures_module["generate_test_dataset"](
            str(test_data_dir), relion_bin, relion_runner,
            num_particles=64,
            size=32,
            angpix=1.0,
        )

        output_dir = test_data_dir / "reconstruction_size"
        output_dir.mkdir(parents=True, exist_ok=True)

        cmd = [
            "mpirun", "-n", "2",
            str(relion_bin / "relion_reconstruct_mpi"),
            "--i", str(test_data_dir / "particles.star"),
            "--o", str(output_dir / "recon_"),
            "--spatial_frequency_mode", "s2",
            "--angpix", "1.0",
        ]

        result = relion_runner(cmd)
        assert result.returncode == 0

        output_map = output_dir / "recon_.spi"
        assert output_map.exists()

        # Spider header + 32³ floats ≈ 131 kB; at least 10 kB to guard against empty file
        assert output_map.stat().st_size > 10_000, (
            f"Output file suspiciously small: {output_map.stat().st_size} bytes"
        )

        # FSC check: same as above, verifies reconstruction quality
        reconstruct_and_check_fsc(
            Path(paths["star_file"]), Path(paths["initial_model"]),
            size=32, angpix=1.0,
            relion_bin=relion_bin, relion_runner=relion_runner,
            output_dir=output_dir,
        )
